apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: appwrite-config
  namespace: appwrite
spec:
  chart: nfs-subdir-external-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  set:
    nfs.server: tnas.local
    nfs.path: /mnt/public/appwrite
    storageClass.name: appwrite-config
    storageClass.reclaimPolicy: Retain
    storageClass.accessModes: ReadWriteMany
    nfs.reclaimPolicy: Retain
