apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appwrite-uploads
  namespace: appwrite
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: appwrite-uploads
  resources:
    requests:
      storage: 2Gi
