apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.32.0 (765fde254)
    traefik.constraint-label-stack: appwrite
    traefik.docker.network: appwrite
    traefik.enable: "true"
    traefik.http.routers.appwrite_api_http.entrypoints: appwrite_web
    traefik.http.routers.appwrite_api_http.rule: PathPrefix(`/`)
    traefik.http.routers.appwrite_api_http.service: appwrite_api
    traefik.http.routers.appwrite_api_https.entrypoints: appwrite_websecure
    traefik.http.routers.appwrite_api_https.rule: PathPrefix(`/`)
    traefik.http.routers.appwrite_api_https.service: appwrite_api
    traefik.http.routers.appwrite_api_https.tls: "true"
    traefik.http.services.appwrite_api.loadbalancer.server.port: "80"
  labels:
    io.kompose.service: appwrite
  name: appwrite
  namespace: appwrite
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appwrite
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.32.0 (765fde254)
        traefik.constraint-label-stack: appwrite
        traefik.docker.network: appwrite
        traefik.enable: "true"
        traefik.http.routers.appwrite_api_http.entrypoints: appwrite_web
        traefik.http.routers.appwrite_api_http.rule: PathPrefix(`/`)
        traefik.http.routers.appwrite_api_http.service: appwrite_api
        traefik.http.routers.appwrite_api_https.entrypoints: appwrite_websecure
        traefik.http.routers.appwrite_api_https.rule: PathPrefix(`/`)
        traefik.http.routers.appwrite_api_https.service: appwrite_api
        traefik.http.routers.appwrite_api_https.tls: "true"
        traefik.http.services.appwrite_api.loadbalancer.server.port: "80"
      labels:
        io.kompose.network/appwrite: "true"
        io.kompose.service: appwrite
    spec:
      containers:
        - image: appwrite/appwrite:1.4.13
          name: appwrite
          volumeMounts:
            - mountPath: /storage/uploads
              name: appwrite-uploads
            - mountPath: /storage/cache
              name: appwrite-cache
            - mountPath: /storage/config
              name: appwrite-config
            - mountPath: /storage/certificates
              name: appwrite-certificates
            - mountPath: /storage/functions
              name: appwrite-functions
          env:
          - name: _APP_ENV
            value: production
          - name: _APP_WORKER_PER_CORE
            value: "6"
          - name: _APP_LOCALE
            value: en
          - name: _APP_CONSOLE_WHITELIST_ROOT
            value: disabled
          - name: _APP_CONSOLE_WHITELIST_EMAILS
            value:
          - name: _APP_CONSOLE_WHITELIST_IPS
            value:
          - name: _APP_SYSTEM_EMAIL_NAME
            value: Appwrite
          - name: _APP_SYSTEM_EMAIL_ADDRESS
            value: team@appwrite.io
          - name: _APP_SYSTEM_SECURITY_EMAIL_ADDRESS
            value: certs@appwrite.io
          - name: _APP_SYSTEM_RESPONSE_FORMAT
            value:
          - name: _APP_OPTIONS_ABUSE
            value: enabled
          - name: _APP_OPTIONS_ROUTER_PROTECTION
            value: disabled
          - name: _APP_OPTIONS_FORCE_HTTPS
            value: disabled
          - name: _APP_OPTIONS_FUNCTIONS_FORCE_HTTPS
            value: disabled
          - name: _APP_OPENSSL_KEY_V1
            value: your-secret-key
          - name: _APP_DOMAIN
            value: localhost
          - name: _APP_DOMAIN_TARGET
            value: localhost
          - name: _APP_DOMAIN_FUNCTIONS
            value: functions.localhost
          - name: _APP_REDIS_HOST
            value: redis-svc.appwrite.svc
          - name: _APP_REDIS_PORT
            value: "6379"
          - name: _APP_REDIS_USER
            value:
          - name: _APP_REDIS_PASS
            value:
          - name: _APP_DB_HOST
            value: mariadb-svc.appwrite.svc
          - name: _APP_DB_PORT
            value: "3306"
          - name: _APP_DB_SCHEMA
            value: appwrite
          - name: _APP_DB_USER
            value: user
          - name: _APP_DB_PASS
            value: password
          - name: _APP_SMTP_HOST
            value:
          - name: _APP_SMTP_PORT
            value:
          - name: _APP_SMTP_SECURE
            value:
          - name: _APP_SMTP_USERNAME
            value:
          - name: _APP_SMTP_PASSWORD
            value:
          - name: _APP_USAGE_STATS
            value: enabled
          - name: _APP_INFLUXDB_HOST
            value: influxdb-svc.appwrite.svc
          - name: _APP_INFLUXDB_PORT
            value: "8086"
          - name: _APP_STORAGE_LIMIT
            value: "30000000"
          - name: _APP_STORAGE_PREVIEW_LIMIT
            value: "20000000"
          - name: _APP_STORAGE_ANTIVIRUS
            value: disabled
          - name: _APP_STORAGE_ANTIVIRUS_HOST
            value: clamav-svc
          - name: _APP_STORAGE_ANTIVIRUS_PORT
            value: "3310"
          - name: _APP_STORAGE_DEVICE
            value: local
          - name: _APP_STORAGE_S3_ACCESS_KEY
            value:
          - name: _APP_STORAGE_S3_SECRET
            value:
          - name: _APP_STORAGE_S3_REGION
            value: us-east-1
          - name: _APP_STORAGE_S3_BUCKET
            value:
          - name: _APP_STORAGE_DO_SPACES_ACCESS_KEY
            value:
          - name: _APP_STORAGE_DO_SPACES_SECRET
            value:
          - name: _APP_STORAGE_DO_SPACES_REGION
            value: us-east-1
          - name: _APP_STORAGE_DO_SPACES_BUCKET
            value:
          - name: _APP_STORAGE_BACKBLAZE_ACCESS_KEY
            value:
          - name: _APP_STORAGE_BACKBLAZE_SECRET
            value:
          - name: _APP_STORAGE_BACKBLAZE_REGION
            value: us-west-004
          - name: _APP_STORAGE_BACKBLAZE_BUCKET
            value:
          - name: _APP_STORAGE_LINODE_ACCESS_KEY
            value:
          - name: _APP_STORAGE_LINODE_SECRET
            value:
          - name: _APP_STORAGE_LINODE_REGION
            value: eu-central-1
          - name: _APP_STORAGE_LINODE_BUCKET
            value:
          - name: _APP_STORAGE_WASABI_ACCESS_KEY
            value:
          - name: _APP_STORAGE_WASABI_SECRET
            value:
          - name: _APP_STORAGE_WASABI_REGION
            value: eu-central-1
          - name: _APP_STORAGE_WASABI_BUCKET
            value:
          - name: _APP_FUNCTIONS_SIZE_LIMIT
            value: "30000000"
          - name: _APP_FUNCTIONS_TIMEOUT
            value: "900"
          - name: _APP_FUNCTIONS_BUILD_TIMEOUT
            value: "900"
          - name: _APP_FUNCTIONS_CPUS
            value: "0"
          - name: _APP_FUNCTIONS_MEMORY
            value: "0"
          - name: _APP_FUNCTIONS_RUNTIMES
            value: node-16.0,php-8.0,python-3.9,ruby-3.0
          - name: _APP_EXECUTOR_SECRET
            value: your-secret-key
          - name: _APP_EXECUTOR_HOST
            value: http://openruntimes-executor-svc.appwrite.svc/v1
          - name: _APP_LOGGING_PROVIDER
            value:
          - name: _APP_LOGGING_CONFIG
            value:
          - name: _APP_STATSD_HOST
            value: telegraf-svc.appwrite.svc
          - name: _APP_STATSD_PORT
            value: "8125"
          - name: _APP_MAINTENANCE_INTERVAL
            value: "86400"
          - name: _APP_MAINTENANCE_RETENTION_EXECUTION
            value: "1209600"
          - name: _APP_MAINTENANCE_RETENTION_CACHE
            value: "2592000"
          - name: _APP_MAINTENANCE_RETENTION_ABUSE
            value: "86400"
          - name: _APP_MAINTENANCE_RETENTION_AUDIT
            value: "1209600"
          - name: _APP_MAINTENANCE_RETENTION_USAGE_HOURLY
            value: "8640000"
          - name: _APP_MAINTENANCE_RETENTION_SCHEDULES
            value: "86400"
          - name: _APP_SMS_PROVIDER
            value:
          - name: _APP_SMS_FROM
            value:
          - name: _APP_GRAPHQL_MAX_BATCH_SIZE
            value: "10"
          - name: _APP_GRAPHQL_MAX_COMPLEXITY
            value: "250"
          - name: _APP_GRAPHQL_MAX_DEPTH
            value: "3"
          - name: _APP_VCS_GITHUB_APP_NAME
            value:
          - name: _APP_VCS_GITHUB_PRIVATE_KEY
            value:
          - name: _APP_VCS_GITHUB_APP_ID
            value:
          - name: _APP_VCS_GITHUB_WEBHOOK_SECRET
            value:
          - name: _APP_VCS_GITHUB_CLIENT_SECRET
            value:
          - name: _APP_VCS_GITHUB_CLIENT_ID
            value:
          - name: _APP_MIGRATIONS_FIREBASE_CLIENT_ID
            value:
          - name: _APP_MIGRATIONS_FIREBASE_CLIENT_SECRET
            value:
          - name: _APP_ASSISTANT_OPENAI_API_KEY
            value:
      restartPolicy: Always
      volumes:
        - name: appwrite-uploads
          persistentVolumeClaim:
            claimName: appwrite-uploads
        - name: appwrite-cache
          persistentVolumeClaim:
            claimName: appwrite-cache
        - name: appwrite-config
          persistentVolumeClaim:
            claimName: appwrite-config
        - name: appwrite-certificates
          persistentVolumeClaim:
            claimName: appwrite-certificates
        - name: appwrite-functions
          persistentVolumeClaim:
            claimName: appwrite-functions
