apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: appwrite-worker-audits
  name: appwrite-worker-audits
  namespace: appwrite
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appwrite-worker-audits
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/appwrite: "true"
        io.kompose.service: appwrite-worker-audits
    spec:
      containers:
        - command:
            - worker-audits
          image: appwrite/appwrite:1.4.13
          name: appwrite-worker-audits
          env:
          - name: _APP_ENV
            value: production
          - name: _APP_WORKER_PER_CORE
            value: "6"
          - name: _APP_OPENSSL_KEY_V1
            value: your-secret-key
          - name: _APP_REDIS_HOST
            value: redis-svc.appwrite.svc
          - name: _APP_REDIS_PORT
            value: "6379"
          - name: _APP_REDIS_USER
            value:
          - name: _APP_REDIS_PASS
            value:
          - name: _APP_DB_HOST
            value: mariadb-svc.appwrite.svc
          - name: _APP_DB_PORT
            value: "3306"
          - name: _APP_DB_SCHEMA
            value: appwrite
          - name: _APP_DB_USER
            value: user
          - name: _APP_DB_PASS
            value: password
          - name: _APP_LOGGING_PROVIDER
            value:
          - name: _APP_LOGGING_CONFIG
            value:
      restartPolicy: Always
