apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appwrite-ingress
  namespace: appwrite
spec:
  defaultBackend:
    service:
      name: appwrite-svc
      port:
        number: 80
  rules:
  - host: "xxxx-xx-xx-xx-x.ngrok-free.app"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: appwrite-svc
            port:
              number: 80
      - pathType: Prefix
        path: "/v1/realtime"
        backend:
          service:
            name: appwrite-realtime-svc
            port:
              number: 80