apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: appwrite-maintenance
  name: appwrite-maintenance
  namespace: appwrite
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appwrite-maintenance
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/appwrite: "true"
        io.kompose.service: appwrite-maintenance
    spec:
      containers:
        - command:
            - maintenance
          image: appwrite/appwrite:1.4.13
          name: appwrite-maintenance
          env:
          - name: _APP_ENV
            value: production
          - name: _APP_WORKER_PER_CORE
            value: "6"
          - name: _APP_DOMAIN
            value: localhost
          - name: _APP_DOMAIN_TARGET
            value: localhost
          - name: _APP_DOMAIN_FUNCTIONS
            value: functions.localhost
          - name: _APP_OPENSSL_KEY_V1
            value: your-secret-key   
          - name: _APP_REDIS_HOST
            value: redis-svc.appwrite.svc
          - name: _APP_REDIS_PORT
            value: "6379"
          - name: _APP_REDIS_USER
            value:
          - name: _APP_REDIS_PASS
            value:
          - name: _APP_DB_HOST
            value: mariadb-svc.appwrite.svc
          - name: _APP_DB_PORT
            value: "3306"
          - name: _APP_DB_SCHEMA
            value: appwrite
          - name: _APP_DB_USER
            value: user
          - name: _APP_DB_PASS
            value: password
          - name: _APP_MAINTENANCE_INTERVAL
            value: "86400"
          - name: _APP_MAINTENANCE_RETENTION_EXECUTION
            value: "1209600"
          - name: _APP_MAINTENANCE_RETENTION_CACHE
            value: "2592000"
          - name: _APP_MAINTENANCE_RETENTION_ABUSE
            value: "86400"
          - name: _APP_MAINTENANCE_RETENTION_AUDIT
            value: "1209600"
          - name: _APP_MAINTENANCE_RETENTION_USAGE_HOURLY
            value: "8640000"
          - name: _APP_MAINTENANCE_RETENTION_SCHEDULES
            value: "86400"
      restartPolicy: Always
