apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: appwrite-worker-builds
  name: appwrite-worker-builds
  namespace: appwrite
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: appwrite-worker-builds
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/appwrite: "true"
        io.kompose.service: appwrite-worker-builds
    spec:
      containers:
        - command:
            - worker-builds
          image: appwrite/appwrite:1.4.13
          name: appwrite-worker-builds
          volumeMounts:
            - mountPath: /storage/functions
              name: appwrite-functions
            - mountPath: /storage/builds
              name: appwrite-builds
          env:
          - name: _APP_ENV
            value: production
          - name: _APP_WORKER_PER_CORE
            value: "6"
          - name: _APP_OPENSSL_KEY_V1
            value: your-secret-key
          - name: _APP_EXECUTOR_SECRET
            value: your-secret-key
          - name: _APP_EXECUTOR_HOST
            value: http://appwrite-executor-svc/v1
          - name: _APP_REDIS_HOST
            value: redis-svc.appwrite.svc
          - name: _APP_REDIS_PORT
            value: "6379"
          - name: _APP_REDIS_USER
            value:
          - name: _APP_REDIS_PASS
            value:
          - name: _APP_DB_HOST
            value: mariadb-svc.appwrite.svc
          - name: _APP_DB_PORT
            value: "3306"
          - name: _APP_DB_SCHEMA
            value: appwrite
          - name: _APP_DB_USER
            value: user
          - name: _APP_DB_PASS
            value: password
          - name: _APP_LOGGING_PROVIDER
            value:
          - name: _APP_LOGGING_CONFIG
            value:
          - name: _APP_VCS_GITHUB_APP_NAME
            value:
          - name: _APP_VCS_GITHUB_PRIVATE_KEY
            value:
          - name: _APP_VCS_GITHUB_APP_ID
            value:
          - name: _APP_FUNCTIONS_TIMEOUT
            value: "900"
          - name: _APP_FUNCTIONS_BUILD_TIMEOUT
            value: "900"
          - name: _APP_FUNCTIONS_CPUS
            value: "0"
          - name: _APP_FUNCTIONS_SIZE_LIMIT
            value: "30000000"
          - name: _APP_OPTIONS_FORCE_HTTPS
            value: disabled
          - name: _APP_OPTIONS_FUNCTIONS_FORCE_HTTPS
            value: disabled
          - name: _APP_DOMAIN
            value: localhost
          - name: _APP_STORAGE_DEVICE
            value: local
          - name: _APP_STORAGE_S3_ACCESS_KEY
            value:
          - name: _APP_STORAGE_S3_SECRET
            value:
          - name: _APP_STORAGE_S3_REGION
            value: us-east-1
          - name: _APP_STORAGE_S3_BUCKET
            value:
          - name: _APP_STORAGE_DO_SPACES_ACCESS_KEY
            value:
          - name: _APP_STORAGE_DO_SPACES_SECRET
            value:
          - name: _APP_STORAGE_DO_SPACES_REGION
            value: us-east-1
          - name: _APP_STORAGE_DO_SPACES_BUCKET
            value:
          - name: _APP_STORAGE_BACKBLAZE_ACCESS_KEY
            value:
          - name: _APP_STORAGE_BACKBLAZE_SECRET
            value:
          - name: _APP_STORAGE_BACKBLAZE_REGION
            value: us-west-004
          - name: _APP_STORAGE_BACKBLAZE_BUCKET
            value:
          - name: _APP_STORAGE_LINODE_ACCESS_KEY
            value:
          - name: _APP_STORAGE_LINODE_SECRET
            value:
          - name: _APP_STORAGE_LINODE_REGION
            value: eu-central-1
          - name: _APP_STORAGE_LINODE_BUCKET
            value:
          - name: _APP_STORAGE_WASABI_ACCESS_KEY
            value:
          - name: _APP_STORAGE_WASABI_SECRET
            value:
          - name: _APP_STORAGE_WASABI_REGION
            value: eu-central-1
          - name: _APP_STORAGE_WASABI_BUCKET
            value:
      restartPolicy: Always
      volumes:
        - name: appwrite-functions
          persistentVolumeClaim:
            claimName: appwrite-functions
        - name: appwrite-builds
          persistentVolumeClaim:
            claimName: appwrite-builds
